### python基础知识：[基础知识链接](https://blog.csdn.net/qxyloveyy/category_9706023.html?spm=1001.2014.3001.5482)
### Numpy基础知识

##### 安装包：pip install numpy

##### 调用包：

In [4]:
from numpy import*

##### 创建数组：

In [8]:
mm=array([1,2,3])
mn=array([[1,2],[3,4]])
print(mm,mn)

[1 2 3] [[1 2]
 [3 4]]


##### 数组加法：

In [9]:
print(mm+array([2,3,4]))


[3 5 7]


##### 数组乘法：

In [10]:
mn*2

array([[2, 4],
       [6, 8]])

##### 数组元素全部平方：


In [11]:
mn**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

##### 访问数组元素：

In [15]:

print('第0行为：',mn[0])

第0行为： [1 2]


In [14]:
print('第0行第一列为：',mn[0,1])

第0行第一列为： 2


##### 两数组对应相乘：

In [18]:
print(mm,array([1,2,3])*mm)

[1 2 3] [1 4 9]


##### 创建矩阵：

In [19]:
mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

##### 矩阵乘法：
##### 对于矩阵AxB需要注意A的列数必须要对于B的行数，否则不能相乘

In [20]:
matA=mat([1,2,3])
matB=mat([[1],[2],[3]])
print(matA*matB)

[[14]]


##### 矩阵的转置和逆以及行列式：
##### 其中逆和行列式是针对方阵而言：

In [24]:
print('矩阵转置：',matA.T)

矩阵转置： [[1]
 [2]
 [3]]


##### 创建一个四阶单位数组：

In [25]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
matN=mat(eye(4))
print('矩阵的逆：',matN.I)

矩阵的逆： [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### 矩阵排序：
##### 获取每个元素的排序序号

In [29]:
matN.argsort()

matrix([[1, 2, 3, 0],
        [0, 2, 3, 1],
        [0, 1, 3, 2],
        [0, 1, 2, 3]], dtype=int64)

In [33]:
print('直接进行排序：')
matN.sort()
matN

直接进行排序：


matrix([[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])

##### 求均值：

In [36]:
matN.mean()

0.25

##### 切片操作：


In [37]:
print('取第一行所有列元素：',matN[0,:])
print('取第一列所有行元素：',matN[:,0])

取第一行所有列元素： [[0. 0. 0. 1.]]
取第一列所有行元素： [[0.]
 [0.]
 [0.]
 [0.]]


### 关于线性代数
##### 标量运算：用一个数字去加或者乘一个矩阵，相当于矩阵中每个元素都加或者乘一个数
##### 两个矩阵能够相乘的前提条件是A的列数要等于B的行数
##### 向量内积：对于两个向量的对应元素相乘并求和
##### 矩阵可逆的前提条件是矩阵的行列式存在（且必须为方阵，行数与列数相等）
##### 某个矩阵不可逆就表示其为奇异或者退化矩阵
##### 矩阵范数：向量的范数运算会给向量赋予一个正标量值，可以把向量范数看作向量的长度

In [20]:
from numpy import*
import pandas as pd
vec=mat([3,4])
print("该向量(L1范数，曼哈顿距离)为：",sum(list(map(abs,vec))))
print("该向量长度为(L2范数)：",sqrt(sum(vec*vec.T)))

该向量(L1范数，曼哈顿距离)为： 7
该向量长度为(L2范数)： 5.0


### 概率论
##### 概率是指一件事情发生的概率
##### 如下图所示

In [53]:
import pandas as pd
id=[i for i in range(1,8)]
dayWeek=[1,2,4,5,1,2,3]
t=[20,24,22,19,12,40,29]
weather=["雨","晴","晴","雨","雪","晴","晴"]
data=pd.DataFrame()
data["编号"]=id
data["星期"]=dayWeek
data["华氏度"]=t
data["天气"]=weather
data

编号  星期  华氏度 天气
0   1   1   20  雨
1   2   2   24  晴
2   3   4   22  晴
3   4   5   19  雨
4   5   1   12  雪
5   6   2   40  晴
6   7   3   29  晴

In [44]:
print("(古典概率)天下雪的概率为：",sum((data["天气"]=="雪")==True)/data.shape[0])

(古典概率)天下雪的概率为： 0.14285714285714285


In [60]:
print("(联合概率)星期二天下雪的概率为：",0)

(联合概率)星期二天下雪的概率为： 0


### 资源介绍：
##### 1.加州大学欧文分校[数据库](http://archive.ics.uci.edu/ml)：包含200多个可以数据集
##### 2.Amazon公开[数据库](https://registry.opendata.aws/),该数据库包含大量数据
##### 3.一个政府公开的[数据库](https://www.data.gov/),该数据库主要包含一些被召回的产品信息
##### 4.Infochimps公司公开的[数据集](https://dev.co/)
